# Site settings
title: Headwindx的技术博客
email: dehengxu@outlook.com
description: "这里只关注移动互联网技术."
baseurl: ""
url: "http://xudeheng.github.io/tech"

# Build settings
markdown: kramdown
permalink: pretty
